services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:password@db:3306/chat_db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:  # Add health check
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data: